name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    env:
      ENTRY_POINT: "main.py"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13.x

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Install dev dependencies
        run: pip install -r dev-requirements.txt

      - name: Build executable
        run: pyinstaller --noconsole ${{ env.ENTRY_POINT }}

      - name: Validate build
        run: ls -R dist

      - name: ${{ matrix.os }} package
        uses: actions/upload-artifact@v4
        with:
          name: RentryArchiver-${{ env.GITHUB_REF_NAME }}-${{ matrix.os }}
          path: dist/
          if-no-files-found: error

  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Collect build artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: RentryArchiver-*
          path: dist/
          merge-multiple: true

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
